#!/bin/sh
#+ Autor:	StackOverflow + Ran#
#+ Creado:	2019
#+ Editado:	16/03/2020 15:29:19

#+ Variables:
#+ $1 > Arquivo concreto	[opcional]
#+ $2 > Nome de saída	[opcional]

# se metes unha variable esa variable en concreto
if [ -n "$1" ]; then

	# se de segundo metes título
	if [ -z "$2" ]; then
		nome=`echo "$1" | cut -d'.' -f1`;

	# se non metes nada de segundo
	else
		nome=`echo "$2"`;	
	fi

	ffmpeg -i "$1" -crf -o "${nome}.ogg";  
	rm "$1"

# se non metes variable toda a carpeta
else
	for i in *.webm or *.mp4 or *.m4a or *.opus; do 
		nome=`echo $i | cut -d'.' -f1`;
  		echo $nome;
  		ffmpeg -i "$i" -crf -o "${nome}.ogg";  
	done
	rm *.webm *.mp4 *.m4a *.opus
fi
