#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	18/03/2020 14:53:03
#+ Editado:	13/06/2020 23:01:04

#* Variables
#* $1 : Texto a copiar na clipboard

# mandamoslle o echo do $1 sen nova linha a xclip quitandolle o intro co xargs co -0 para poder ter cominha simple no texto
echo -n $1 | xargs -0 echo -n | xclip -selection clipboard
