#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	18/03/2020 14:53:03
#+ Editado:	29/07/2020 21:10:38

#-------------------------------------
#* Variables
#* [$1] : Texto a copiar na clipboard
#-------------------------------------

# miramos por stdin e por parametros a mensaxe. Prioriza os parámetros de haber ambos
[ -z "$1" ] && mensaxe=$(cat -) || mensaxe="$1"

# mandamoslle o echo da mensaxe sen nova linha a xclip quitandolle o intro co xargs co -0 para poder ter cominha simple no texto
echo -n $mensaxe | xargs -0 echo -n | xclip -selection clipboard
