#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/03/2020 00:07:50
#+ Editado:	08/03/2020 00:13:17

#* Script para copiar os scripts básicos directamente a /usr/local/bin

cp metadata rmswaps vel 2ogg 2pdf git-commit git-downfile git-local pomodoro.py /usr/local/bin
