#! /bin/bash
#+ Autor:	Ran# + StackOverflow
#+ Creado:	2019
#+ Editado:	14/06/2020 15:27:53

now=$(date +%s)sec

while true
do
	printf "%s\r" $(TZ=UTC date --date now-$now +%H:%M:%S:%N)
	sleep 0.1
done
