#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	03/07/2019 22:56:46
#+ Editado:	28/07/2020 23:22:25

#* Variables:
#* $1 > Mensaxe de comit [opcional]

# pon a info local de usuario e correo
gl

# engade tódolos cambios ao comit
git add .

# se metes unha mensaxe de commit mandamos esa
if [ -n "$1" ]; then
	git commit -m "$1"
# senón mándase unha por defecto
else
	git commit -m "cambios"
fi

# empuxamos os cambios
git push
