#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	03/07/2019 22:56:46
#+ Editado:	12/03/2020 13:15:37

git add .

# se metes unha mensaxe de commit mandamos esa
if [ -n "$1" ]; then
	git commit -m "$1"
# senón mándase unha por defecto
else
	git commit -m "cambios"
fi

git push
