#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	09/07/2019 19:47:42
#+ Editado:	09/07/2019 20:08:20

usrep=$(echo "$1"|cut -d'/' -f 4-5)
fich=$(echo "$1"|cut -d'/' -f 7-)

wget https://raw.githubusercontent.com/$usrep/$fich
