#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	13/06/2020 22:36:20
#+ Editado:	13/06/2020 22:38:50

# dalle a volta ao pwd, parte por / e colle o primeiro campo e desfai o rev
carpeta=$(pwd | rev | cut -d/ -f1 | rev)

copia "$carpeta"
