#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	13/06/2020 22:36:20
#+ Editado:	16/06/2020 23:09:58

# dalle a volta ao pwd, parte por / e colle o primeiro campo e desfai o rev
pwd | rev | cut -d/ -f1 | rev | copia
