#! /bin/bash
#+ Autor:	Ran#
#+ Creado:	05/06/2019
#+ Editado:	28/07/2020 23:33:43

#* Variables
#* $1 	: Tipo de acción a realizar
#* [$2] : Nome do ficheiro a editar

data=$(date +%d/%m/%Y\ %R:%S)

# miramos por stdin e por parámetros o nome. Prioriza os parámetros de haber ambos
[ -z "$2" ] && fich=$(cat -) || fich="$2"

case $1 in
	"-e"|"--editado")
		sed -i "s|^#+ Editado:.*|#+ Editado:\t$data|" $fich
		;;

	"-c"|"--creado")
		sed -i "s|^#!\(.*\)|#!\1\n#+ Autor:\tRan#\n#+ Creado:\t$data\n#+ Editado:\t$data|" $fich
		;;

	"-a"|"--axuda"|"?")
		echo -e "-e, --editado\t> cambiar data de edición."
		echo -e "-c, --creado\t> inserir as liñas de autor, creado e editado por primeira vez."
		echo -e "-?,-a, --axuda\t> imprimir este mensaxe."
		echo -e "-m, --mostrala\t> imprimir a metadata do ficheiro."
		echo -e "-s, --suprimir\t> suprimir a metadata do ficheiro."
		;;

	"-m"|"--mostrarla")
		grep "^#+" $fich
		;;
	
	"-s"|"--suprimir")
		sed -i "/^#+.*/d" $fich
		;;

	*)
		echo "Editado (-e), creado (-c), axuda (-a), mostrar metadata (-m)"
		;;
esac
