#!/bin/sh
#+ Autor:	Ran#
#+ Creado:	04/2019
#+ Editado:	10/06/2019 17:17:19

if [ ! -z $(find . -type f -mmin 0.1 | grep $1.ms) ]
then
	groff -ms $1.ms -T pdf -K utf8 > $1.pdf
else
	echo Sen cambios
fi
