#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	01/06/2020 22:04:00
#+ Editado:	01/06/2020 22:27:10

printf "\nId Partición \t Punto de Montado\n"
echo "------------    ----------------"
mount -v | grep "^/" | awk '{print $1  "\t"  $3 "\n"}'
