#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	11/06/2020 13:13:35
#+ Editado:	16/06/2020 23:08:13

#------------------------------------
#* Variables
#* $1 :	Nome da rede [OPCIONAL]
#------------------------------------

REDE='Nome'

# se mete un -a e que quere a rede actual
if [ "$1" = "-m" ]; then
	# mostramos todas as redes gardadas
	echo 'Redes:'
	sudo ls /etc/NetworkManager/system-connections/ | cut -d. -f1
	echo ''
	# dialogo para que nos pegue o nome da rede que queremos
	read -p "Pega o nome da rede que queres tal cal está: " REDE
	echo ''

# se nos mete un argumento xa suponhemos que mete o nome da rede ben posto
elif [ "$1" = "-r" ]; then
	REDE="$2"
elif [ "$1" = "?" ]; then
	echo ''
	echo "Información:"
	echo "-----------------------------------"
	echo " ? -> axuda"
	echo "-m -> mostra todos os nomes posibles"
	echo "-r -> nome da rede por parámetro"
	echo "-----------------------------------"
	exit 0
else
	REDE="$(nmcli | sed 1q | awk -F 'to ' '{print $2}')"
fi

# mostrámoslle o constrasinal da rede en texto plano
contrasinal=$(sudo cat /etc/NetworkManager/system-connections/"$REDE".nmconnection | grep ^psk | cut -d= -f2)

echo $contrasinal
copia $contrasinal
