#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	11/06/2020 13:13:35
#+ Editado:	11/06/2020 13:33:37

#------------------------------------
#* Variables
#* $1 :	Nome da rede [OPCIONAL]
#------------------------------------

# se nos mete un argumento xa suponhemos que mete o nome da rede ben posto
[ -z "$1" ] || { 
	sudo cat /etc/NetworkManager/system-connections/"$1".nmconnection | grep ^psk | cut -d= -f2;
	# saímos sen erro
	exit 0;
}

# mostramos todas as redes gardadas
echo 'Redes:'
sudo ls /etc/NetworkManager/system-connections/ | cut -d. -f1
echo ''
# dialogo para que nos pegue o nome da rede que queremos
read -p "Pega o nome da rede que queres: " WIFI
echo ''
# mostrámoslle o constrasinal da rede en texto plano
sudo cat /etc/NetworkManager/system-connections/"$WIFI".nmconnection | grep ^psk | cut -d= -f2
