#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	21/03/2020 12:55:47
#+ Editado:	21/03/2020 15:44:37


#* Variables
#* $1 : ligazón
#* $2 : título
#* $3 : autor
#* $4 : ogg	[opcional DESACTIVADA]

# por se non metes argumentos
[ $# -eq 0 ] && exit 0

# se metemos -a como primeiro elemento mensaxe de axuda e pirarse
[ $1 == "-a" ] && { printf "Opcións: \n";
		    printf "\t -a : Axuda, mostra esta mensaxe.\n";
		    printf "Orde dos elementos:\n";
		    printf "\t LIGAZÓN TÍTULO AUTOR\n";
		     exit 1;
	    	   }

# mira o count das variables, se é menor a 3 decimos que meta tódalas variables
[ $# -lt 3 ] && { printf "Pon tódalas opcións. Para axuda -a.\n";
		  exit 0;
	  	}

# eu quero todos baixados así pero para que se poda editar facil
youtube-dl -x -o "$2 ~ $3.(ext)s" $1 --recode-video ogg

# se metes 4 elemtos
#[ $# -eq 4 ] && { [ $4 == "-ogg" ] && youtube-dl -x -o "$2 ~ $3.(ext)s" $1 --recode-video ogg; exit 1; }
#if [ $# -eq 4 ]; then
	# mira que sexa ogg o último, se o é baixaoo como ogg senón feira
#	[ $4 == "-ogg" ] && youtube-dl -x -o "$2 ~ $3.(ext)s" $1 --recode-video ogg
#	exit 0
#fi

# se non ten 4 eltos baixaoo feira 
#youtube-dl -x -o "$2 ~ $3.(ext)s" $1
