#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	21/03/2020 12:55:47
#+ Editado:	27/05/2020 19:22:14


#* Variables
#* $1 : ligazón
#* $2 : autor
#* $3 : título
#* $4 : extensión dinámica [OPCIONAL]

SEPARADOR='~'
EXTENSION='flac' # mp4 flv ogg webm mkv avi flac

# se non metes os argumentos que son mostra a axuda
[ $# -lt 3 ] && {
		 printf "Orde dos elementos a incluir:\n";
                 printf "Ligazón Autor Título [Extensión]\n";
                 exit 1;
		}

# CONVERSIÓN ESTÁTICA, DADA POLA VARIABLE. SEMPRE A MESMA.
# eu quero todos baixados así pero para que se poda editar fácil
youtube-dl --add-metadata -i -x -f bestaudio/best -o "$2 $SEPARADOR $3.(ext)s" $1 --audio-format $EXTENSION --audio-quality 9

# CONVERSIÓN DINÁMICA, COA EXTENSIÓN DADA POR COMANDOS
# se metes 4 elemtos o 4º é a extensión que queres e cambiacho a esa, senón baixa sen conversión
#[ $# -eq 4 ] && { 
#		youtube-dl -x -o "$2 $SEPARADOR $3.(ext)s" $1 --recode-video $4;
#		exit 1; 
#		} || 
#		youtube-dl -x -o "$2 $SEPARADOR $3.(ext)s" $1
