#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/06/2019 13:16:09
#+ Editado:	21/06/2020 13:29:24

echo ''

case $1 in
	-s)
		curl -s 'https://aur.archlinux.org/packages/?K='"$2"'&SB=p' | grep '<td' | cut -d\> -f2,3 | cut -d\" -f3 | cut -d\< -f1 | sed '/^[0-9]/ d' | sed 's/>//g'
		;;
	-i)
		# -p fai que non saia erro se xa existe e crea todas as carpetas pai precisas se non existen
		mkdir -p ~/Programas

		git clone https://aur.archlinux.org/"$2".git ~/Programas/"$2"

		#chown $USER:$USER ~/Software/"$1"
		cd ~/Programas/"$2"

		makepkg -sirc --noconfirm
		;;
	?)
		echo '? para axuda'
		echo '-i para instalar dado un nome'
		echo '-s para buscar por palabra'
esac


