#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/06/2019 13:16:09
#+ Editado:	07/03/2020 22:50:55

# -p fai que non saia erro se xa existe e crea todas as carpetas pai precisas se non existen
mkdir -p ~/Programas

git clone https://aur.archlinux.org/"$1".git ~/Programas/"$1"

#chown $USER:$USER ~/Software/"$1"
cd ~/Programas/"$1"

makepkg -sirc --noconfirm
