#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/03/2020 13:31:26
#+ Editado:	13/03/2020 07:55:42

printf "Creando ou modificando os nomes das carpetas...\t"
mv ~/Desktop ~/Escritorio 2> /dev/null
mkdir -p ~/Escritorio

mv ~/Documents ~/Documentos 2> /dev/null
mkdir -p ~/Documentos

mv ~/Downloads ~/Descargas 2> /dev/null
mkdir -p ~/Descargas

mv ~/Music ~/Música 2> /dev/null
mkdir -p ~/Musica

mv ~/Pictures ~/Imaxes 2> /dev/null
mkdir -p ~/Imaxes

mv ~/Public ~/Público 2> /dev/null
mkdir -p ~/Publico

mv ~/Software ~/Programas 2> /dev/null
mkdir -p ~/Programas

mv ~/Videos ~/Vídeos 2> /dev/null
mkdir -p ~/Vídeos

printf "OK\n"
