#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/03/2020 00:07:50
#+ Editado:	21/03/2020 20:04:59

#* Script para copiar os scripts básicos directamente a /usr/local/bin

printf "Copiando os scripts básicos a /usr/local/bin...\t"
cp ydlv ydla metadata rmswaps vel 2ogg 2pdf gc gdf gl pomodoro.py aleatorio conversor copia /usr/local/bin
printf "OK\n"
