#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/03/2020 00:07:50
#+ Editado:	08/03/2020 17:10:58

#* Script para copiar os scripts básicos directamente a /usr/local/bin

printf "Copiando os scripts básicos a /usr/local/bin...\t"
cp metadata rmswaps vel 2ogg 2pdf gc gdf gl pomodoro.py /usr/local/bin
printf "OK\n"
